In [3]:
import pandas as pd

df = pd.read_parquet('../rust-ingest/pcap_samples/ny4-small-10m_parsed.parquet')
df.shape

(10000000, 4)

In [4]:
df.head()

   packet_index  udp_payload_len  block_size  messages_in_block
0             0              108         108                  3
1             1               50          50                  1
2             2              166         166                  5
3             3               50          50                  1
4             4              108         108                  3

In [5]:
df.tail()

         packet_index  udp_payload_len  block_size  messages_in_block
9999995       9999995               50          50                  1
9999996       9999996               50          50                  1
9999997       9999997               50          50                  1
9999998       9999998               50          50                  1
9999999       9999999              138         138                  4