In [8]:
import pandas as pd

trades_df = pd.read_parquet('../rust-ingest/pcap_samples/ny4-small-10k_trades.parquet')
print(trades_df['category'].unique())
print(trades_df.shape)
display(trades_df.head())
display(trades_df.tail())

['q']
(14440, 20)

,packet_index,block_sequence,block_timestamp_ns,block_timestamp_utc,message_index_in_block,participant,category,type_code,indicator,symbol_root,osi_symbol,bid,ask,bid_size,ask_size,price,size,side,action,flags
0,0,355512323,1692714599999800576,2023-08-22T14:29:59.999800576Z,0,C,q,A,A,SPY,SPY 230830P00423000,0.48,0.50,310,418,NaN,NaN,None,None,NaN
1,0,355512323,1692714599999800576,2023-08-22T14:29:59.999800576Z,1,C,q,A,A,SPY,SPY 230822P00439000,0.78,0.80,45,434,NaN,NaN,None,None,NaN
2,0,355512323,1692714599999800576,2023-08-22T14:29:59.999800576Z,2,C,q,A,A,SPY,SPY 230825P00438000,2.25,2.28,121,193,NaN,NaN,None,None,NaN
3,1,207634110,1692714599999804416,2023-08-22T14:29:59.999804416Z,0,C,q,A,A,SPY,SPY 240315C00455000,17.76,17.90,207,212,NaN,NaN,None,None,NaN
4,2,263110673,1692714599999802624,2023-08-22T14:29:59.999802624Z,0,C,q,A,A,SPY,SPY 230823C00442000,0.92,0.94,350,52,NaN,NaN,None,None,NaN

,packet_index,block_sequence,block_timestamp_ns,block_timestamp_utc,message_index_in_block,participant,category,type_code,indicator,symbol_root,osi_symbol,bid,ask,bid_size,ask_size,price,size,side,action,flags
14435,9997,263119048,1692714600031779072,2023-08-22T14:30:00.031779072Z,0,Q,q,,A,SPY,SPY 230828C00435000,6.62,6.67,6,70,NaN,NaN,None,None,NaN
14436,9998,207639644,1692714600031791104,2023-08-22T14:30:00.031791104Z,0,H,q,,A,SPY,SPY 230929C00295000,145.12,146.31,44,44,NaN,NaN,None,None,NaN
14437,9998,207639644,1692714600031791104,2023-08-22T14:30:00.031791104Z,1,Q,q,,A,SPY,SPY 230929C00329000,111.33,112.52,2,1,NaN,NaN,None,None,NaN
14438,9998,207639644,1692714600031791104,2023-08-22T14:30:00.031791104Z,2,I,q,,A,SPY,SPY 230908C00447500,2.36,2.39,144,96,NaN,NaN,None,None,NaN
14439,9999,355521879,1692714600031791872,2023-08-22T14:30:00.031791872Z,0,H,q,,A,SPY,SPY 230831P00467000,26.85,28.04,33,55,NaN,NaN,None,None,NaN

In [2]:
import pandas as pd

# trades_df = pd.read_parquet('../rust-ingest/pcap_samples/ny4-small-1m_trades.parquet')
trades_df = pd.read_parquet('../rust-ingest/pcap_samples/ny4-small-10m_trades.parquet')
print(trades_df['category'].unique())
print(trades_df['category'].value_counts())
print(trades_df['category'].value_counts(normalize=True))
print(trades_df.shape)
display(trades_df.head())
display(trades_df.tail())

['q' 'a']
category
q    12262190
a        1921
Name: count, dtype: int64
category
q    0.999843
a    0.000157
Name: proportion, dtype: float64
(12264111, 20)

,packet_index,block_sequence,block_timestamp_ns,block_timestamp_utc,message_index_in_block,participant,category,type_code,indicator,symbol_root,osi_symbol,bid,ask,bid_size,ask_size,price,size,side,action,flags
0,0,355512323,1692714599999800576,2023-08-22T14:29:59.999800576Z,0,C,q,A,A,SPY,SPY 230830P00423000,0.48,0.50,310.0,418.0,NaN,NaN,None,None,NaN
1,0,355512323,1692714599999800576,2023-08-22T14:29:59.999800576Z,1,C,q,A,A,SPY,SPY 230822P00439000,0.78,0.80,45.0,434.0,NaN,NaN,None,None,NaN
2,0,355512323,1692714599999800576,2023-08-22T14:29:59.999800576Z,2,C,q,A,A,SPY,SPY 230825P00438000,2.25,2.28,121.0,193.0,NaN,NaN,None,None,NaN
3,1,207634110,1692714599999804416,2023-08-22T14:29:59.999804416Z,0,C,q,A,A,SPY,SPY 240315C00455000,17.76,17.90,207.0,212.0,NaN,NaN,None,None,NaN
4,2,263110673,1692714599999802624,2023-08-22T14:29:59.999802624Z,0,C,q,A,A,SPY,SPY 230823C00442000,0.92,0.94,350.0,52.0,NaN,NaN,None,None,NaN

,packet_index,block_sequence,block_timestamp_ns,block_timestamp_utc,message_index_in_block,participant,category,type_code,indicator,symbol_root,osi_symbol,bid,ask,bid_size,ask_size,price,size,side,action,flags
12264106,9999994,362818486,1692714679275253248,2023-08-22T14:31:19.275253248Z,0,I,q,,E,SPY,SPY 231229P00360000,2.50,2.54,315.0,213.0,NaN,NaN,None,None,NaN
12264107,9999995,211929206,1692714679275259648,2023-08-22T14:31:19.275259648Z,0,H,q,,A,SPY,SPY 230915C00445000,4.16,4.27,18.0,153.0,NaN,NaN,None,None,NaN
12264108,9999996,362818487,1692714679275268352,2023-08-22T14:31:19.275268352Z,0,T,q,,F,SPY,SPY 231215P00378000,3.12,3.14,137.0,185.0,NaN,NaN,None,None,NaN
12264109,9999997,310934282,1692714679275270656,2023-08-22T14:31:19.275270656Z,0,D,q,,A,SPY,SPY 230929P00437000,7.25,7.28,20.0,15.0,NaN,NaN,None,None,NaN
12264110,9999998,362818488,1692714679275278336,2023-08-22T14:31:19.275278336Z,0,Q,q,,A,SPY,SPY 231215P00399000,4.94,4.98,31.0,33.0,NaN,NaN,None,None,NaN

In [3]:
# show 'a' actual trade messages
display(trades_df[trades_df['category'] == 'a'].head())

,packet_index,block_sequence,block_timestamp_ns,block_timestamp_utc,message_index_in_block,participant,category,type_code,indicator,symbol_root,osi_symbol,bid,ask,bid_size,ask_size,price,size,side,action,flags
43786,34692,355538012,1692714600170725888,2023-08-22T14:30:00.170725888Z,0,E,a,a,,SPY,SPY 230822P00436000,NaN,NaN,NaN,NaN,0.13,1.0,None,a,0.0
55310,43809,304918132,1692714600251444992,2023-08-22T14:30:00.251444992Z,0,C,a,I,,SPY,SPY 230901P00413000,NaN,NaN,NaN,NaN,0.32,1.0,None,I,0.0
106146,79874,207676635,1692714600494317056,2023-08-22T14:30:00.494317056Z,0,T,a,I,,SPY,SPY 230915C00475000,NaN,NaN,NaN,NaN,0.04,58.0,None,I,0.0
128906,97304,355591063,1692714600564975616,2023-08-22T14:30:00.564975616Z,0,C,a,I,,SPY,SPY 231020P00350000,NaN,NaN,NaN,NaN,0.62,33.0,None,I,0.0
133860,100954,304960636,1692714600577837568,2023-08-22T14:30:00.577837568Z,0,M,a,I,,SPY,SPY 230915P00350000,NaN,NaN,NaN,NaN,0.12,33.0,None,I,0.0

In [1]:
import os
import databento as db
from dotenv import load_dotenv

load_dotenv('./.env')

client = db.Historical(os.getenv("DATABENTO_API_KEY"))  # uses DATABENTO_API_KEY env var
db_trades = client.timeseries.get_range(
    dataset="OPRA.PILLAR",
    schema="cmbp-1",                
    # symbols=["SPY.OPT"], 
    # stype_in="parent",                   # request the chain; filter in code
    stype_in="raw_symbol",
    symbols=["SPY   230830P00423000"],
    start="2023-08-22T14:29:59.990000Z",
    end="2023-08-22T14:30:00.500000Z",
    limit=100
).to_df()
print(db_trades.shape)
display(db_trades.head())
print(db_trades.symbol.unique())

(8, 17)

,ts_event,rtype,publisher_id,instrument_id,action,side,price,size,flags,ts_in_delta,bid_px_00,ask_px_00,bid_sz_00,ask_sz_00,bid_pb_00,ask_pb_00,symbol
ts_recv,,,,,,,,,,,,,,,,,
2023-08-22 14:29:59.991083538+00:00,2023-08-22 14:29:59.990872832+00:00,177,30,654312856,A,N,0.49,271,194,0,0.48,0.49,1497,271,0,0,SPY 230830P00423000
2023-08-22 14:30:00.048469173+00:00,2023-08-22 14:30:00.048260352+00:00,177,30,654312856,A,N,0.49,271,194,0,0.48,0.49,1670,271,0,0,SPY 230830P00423000
2023-08-22 14:30:00.075664939+00:00,2023-08-22 14:30:00.075455488+00:00,177,30,654312856,A,N,0.49,321,194,0,0.48,0.49,1670,321,0,0,SPY 230830P00423000
2023-08-22 14:30:00.106431944+00:00,2023-08-22 14:30:00.106223616+00:00,177,30,654312856,A,N,0.49,321,194,0,0.48,0.49,1423,321,0,0,SPY 230830P00423000
2023-08-22 14:30:00.449679234+00:00,2023-08-22 14:30:00.449470208+00:00,177,30,654312856,A,N,0.49,271,194,0,0.48,0.49,1423,271,0,0,SPY 230830P00423000

['SPY   230830P00423000']

In [7]:
trades_df['category'].unique()

array(['q'], dtype=object)

In [3]:
# Compare Rust decoded trades parquet vs DataBento pull (10k window)

symbol = 'SPY   230830P00423000'
START = '2023-08-22T14:29:59.990000Z'
END   = '2023-08-22T14:30:00.500000Z'

trades_df = trades_df[trades_df['symbol'] == symbol]
db_trades = db_trades[db_trades['symbol'] == symbol]
print(trades_df.shape)
display(trades_df.head())
print(db_trades.shape)
display(db_trades.head())

(6, 19)

,ts_event,ts_recv,ts_event_utc,rtype,publisher_id,instrument_id,action,side,price,size,flags,ts_in_delta,bid_px_00,ask_px_00,bid_sz_00,ask_sz_00,bid_pb_00,ask_pb_00,symbol
0,1692714599999800576,1692714599999800576,2023-08-22T14:29:59.999800576Z,177,30,NaN,A,A,0.5,418.0,NaN,0,0.48,0.5,310,418,0,0,SPY 230830P00423000
1820,1692714600005955584,1692714600005955584,2023-08-22T14:30:00.005955584Z,177,30,NaN,C,A,0.5,191.0,NaN,0,0.48,0.5,5,191,0,0,SPY 230830P00423000
2045,1692714600006426368,1692714600006426368,2023-08-22T14:30:00.006426368Z,177,30,NaN,C,A,0.5,698.0,NaN,0,0.48,0.5,520,698,0,0,SPY 230830P00423000
2780,1692714600007849728,1692714600007849728,2023-08-22T14:30:00.007849728Z,177,30,NaN,C,A,0.5,1308.0,NaN,0,0.48,0.5,639,1308,0,0,SPY 230830P00423000
7427,1692714600014484480,1692714600014484480,2023-08-22T14:30:00.014484480Z,177,30,NaN,C,A,0.5,138.0,NaN,0,0.48,0.5,5,138,0,0,SPY 230830P00423000

(8, 17)

,ts_event,rtype,publisher_id,instrument_id,action,side,price,size,flags,ts_in_delta,bid_px_00,ask_px_00,bid_sz_00,ask_sz_00,bid_pb_00,ask_pb_00,symbol
ts_recv,,,,,,,,,,,,,,,,,
2023-08-22 14:29:59.991083538+00:00,2023-08-22 14:29:59.990872832+00:00,177,30,654312856,A,N,0.49,271,194,0,0.48,0.49,1497,271,0,0,SPY 230830P00423000
2023-08-22 14:30:00.048469173+00:00,2023-08-22 14:30:00.048260352+00:00,177,30,654312856,A,N,0.49,271,194,0,0.48,0.49,1670,271,0,0,SPY 230830P00423000
2023-08-22 14:30:00.075664939+00:00,2023-08-22 14:30:00.075455488+00:00,177,30,654312856,A,N,0.49,321,194,0,0.48,0.49,1670,321,0,0,SPY 230830P00423000
2023-08-22 14:30:00.106431944+00:00,2023-08-22 14:30:00.106223616+00:00,177,30,654312856,A,N,0.49,321,194,0,0.48,0.49,1423,321,0,0,SPY 230830P00423000
2023-08-22 14:30:00.449679234+00:00,2023-08-22 14:30:00.449470208+00:00,177,30,654312856,A,N,0.49,271,194,0,0.48,0.49,1423,271,0,0,SPY 230830P00423000